[extend]
useDefault = true

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(?:key|api|token|secret|client|passwd|password|auth|access)(?:[0-9a-z\-_\t .]{0,20})(?:[\s|']|[\s|"]){0,3}(?:=|>|:{1,3}=|\|\|:|<=|=>|:|\?=)(?:'|\"|\s|=|\x60){0,5}([0-9a-z\-_.=]{10,150})(?:['|\"|\n|\r|\s|\x60|;]|$)'''
entropy = 3.5
secretGroup = 1
keywords = ["key", "api", "token", "secret", "client", "passwd", "password", "auth", "access"]

[[rules.allowlist]]
paths = [
    '''docs/deployment/aws-rds-encryption\.md$''',
]
regexTarget = "line"

[allowlist]
paths = [
    '''\.gitleaks\.toml$''',
]
