---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.11
  - pip
  # vcf-pg-loader is installed via pip or container
  # pip install vcf-pg-loader
